return {
	Main = {
		{Text = "Sceleratis/Davey_Bones",	Desc = "Made Adonis & EISS"};
		{Text = "Kohltastrophe (Scripth)",	Desc = "For his help with various things and some code"};
		{Text = "einsteinK",				Desc = "Helped me with some scripting problems early in development and put together the LoadstringParser; Best programmer I know"};
		{Text = "Rerumu (Shining_Diamando)",Desc = "Numerous contributions (Endless stairs, FiOne, Parser, Steampunk theme)"};
		{Text = "Cald_fan", 				Desc = "Community Maintainer & WebPanel Creator & Maintainer"};
		{Text = "joritochip",				Desc = "Community Maintainer & WebPanel Developer"};
		{Text = "Coasterteam",				Desc = "Community Maintainer & Development contributions (Kronos developer)"};
		{Text = "Expertcoderz",				Desc = "Community Maintainer"};
		{Text = "Dimenpsyonal",				Desc = "Community Maintainer"};
	};

	Contributors = {
		{Text = "@MudockYatho", 		Desc = "Open Source Contributor"};
		{Text = "@TheCakeChicken", 	Desc = "Open Source Contributor"};
		{Text = "@NNickey", 			Desc = "Open Source Contributor"};
		{Text = "@FungusGenerator", 	Desc = "Open Source Contributor"};
		{Text = "@ItsGJK", 			Desc = "Open Source Contributor"};
		{Text = "@Kan18", 			Desc = "Open Source Contributor"};
		{Text = "@Brandon-Beck", 	Desc = "Open Source Contributor"};
		{Text = "@GeneralScripter", 	Desc = "Open Source Contributor"};
		{Text = "@moo1210", 			Desc = "Open Source Contributor"};
		{Text = "@kent911t", 		Desc = "Open Source Contributor"};
		{Text = "@crywink", 			Desc = "Open Source Contributor"};
		{Text = "@jaydensar", 		Desc = "Open Source Contributor"};
		{Text = "@ccuser44",			Desc = "Open Source Contributor"};
		{Text = "@Awesomewebm", 		Desc = "Open Source Contributor"};
		{Text = "@TheLegendarySpark",Desc = "Open Source Contributor"};
		{Text = "@EasternBloxxer",			Desc = "Open Source Contributor"};
		{Text = "@LiveFireExercise",	Desc = "Open Source Contributor"};
		{Text = "@policetonyR",		Desc = "Open Source Contributor"};
		{Text = "@enescglyn",		Desc = "Open Source Contributor"};
		{Text = "@EpicFazbear",		Desc = "Open Source Contributor"};
		{Text = "@p3tray",			Desc = "Open Source Contributor"};
		{Text = "@okgabe",			Desc = "Open Source Contributor"};
		{Text = "@fxeP1",			Desc = "Open Source Contributor"};
		{Text = "@optimisticside",	Desc = "Open Source Contributor"};
		{Text = "@NeoInversion",		Desc = "Open Source Contributor"};
		{Text = "@imskyyc",			Desc = "Open Source Contributor"};
		{Text = "@LolloDev5123",		Desc = "Open Source Contributor"};
		{Text = "@happyman090",		Desc = "Open Source Contributor"};
		{Text = "@GalacticInspired",	Desc = "Open Source Contributor"};
		{Text = "@flgx16",			Desc = "Open Source Contributor"};
		{Text = "@DrewBokman",		Desc = "Open Source Contributor"};
		{Text = "@Kw6m",				Desc = "Open Source Contributor"};
		{Text = "@chexburger",		Desc = "Open Source Contributor"};
		{Text = "@TjeerdoBoy112",	Desc = "Open Source Contributor"};
		{Text = "@Jack5079",			Desc = "Open Source Contributor"};
		{Text = "@Bulldo344",		Desc = "Open Source Contributor"};
		{Text = "@evanultra01",		Desc = "Open Source Contributor"};
		{Text = "@SlipperySpelunky",	Desc = "Open Source Contributor"};
		{Text = "@c6lvnss",			Desc = "Open Source Contributor"};
		{Text = "@karl-police",		Desc = "Open Source Contributor"};
		{Text = "@CommodoreGamer118",Desc = "Open Source Contributor"};
		{Text = "@spaggos",			Desc = "Open Source Contributor"};
		{Text = "@jun022222222",		Desc = "Open Source Contributor"};
		{Text = "@sea4h",			Desc = "Open Source Contributor"};
		{Text = "@Tj33rd",			Desc = "Open Source Contributor"};
		{Text = "@DaRealGandhi20",	Desc = "Open Source Contributor"};
		{Text = "@L8X",				Desc = "Open Source Contributor"};
		{Text = "@Honzzzox",			Desc = "Open Source Contributor"};
		{Text = "@Smaltin", 			Desc = "Open Source Contributor"};
		{Text = "@NoUserSet", 		Desc = "Open Source Contributor"};
		{Text = "@xvarmkorv2",		Desc = "Open Source Contributor"};
		{Text = "@Quantify_RBLX",	Desc = "Open Source Contributor"};
		{Text = "@xhayper",			Desc = "Open Source Contributor"};
		{Text = "@NoobBucket",		Desc = "Open Source Contributor"};
		{Text = "@GGshor",			Desc = "Open Source Contributor"};
		{Text = "@WideManHost",		Desc = "Open Source Contributor"};
		{Text = "@autodoorsdev",		Desc = "Open Source Contributor"};
		{Text = "@Lethalitics",		Desc = "Open Source Contributor"};
		{Text = "@Deniernal354",		Desc = "Open Source Contributor"};
		{Text = "@RoyallyFlushed",	Desc = "Open Source Contributor"};
		{Text = "@supercoolspy",		Desc = "Open Source Contributor"};
		{Text = "@AlexanderDarmody",	Desc = "Open Source Contributor"};
		{Text = "@watameln",			Desc = "Open Source Contributor"};
		{Text = "@bigbenster702",	Desc = "Open Source Contributor"};
		{Text = "@WalkerOfBacon", 	Desc = "Open Source Contributor"};
		{Text = "@wilsontulus", 	Desc = "Open Source Contributor"};
		{Text = "@RealEthanPlayzDev", Desc = "Open Source Contributor"};
		{Text = "@Redfuire", Desc = "Open Source Contributor"};
		{Text = "@RadiantUwU", Desc = "Open Source Contributor"};
		{Text = "@kaiserandaxl", Desc = "Open Source Contributor"};
	};

	Misc = {
		{Text = "Kein-Hong Man",			Desc = "Creator of the Yueliang (Lua bytecode compiler in loadstring module). Also created LuLu VM, the first Lua bytecode interpreter used in Adonis (no longer used)"};
		{Text = "Stravant/JustAPerson",		Desc = "Wrote LBI (no longer used)"};
		{Text = "darkelementallord",		Desc = "Updated some guis"};
		{Text = "TheFurryFish",				Desc = "Gave me some dank ideas like local particles and some loading related things; and helped debug"};
		{Text = "Moistality",				Desc = "Helped with finding and patching vulns"};
		{Text = "GigsD4X/F3X",				Desc = "F3X Building Tool"};
		{Text = "Drezmor",					Desc = "Resize was originally ripped from his ohgals and modified"};
		{Text = "KingKeith55",				Desc = "Provided the Stickify command"};
		{Text = "NickPatella",				Desc = "Made the piano used in the !piano command"};
		{Text = "Raspberry Pi/Raspy_Pi", 	Desc = "Made Dex explorer"};
		{Text = "j1my3p1x",					Desc = "His replication checking idea is what lead to the replication logs"};
		{Text = "Bubby4j",					Desc = "Used their \"Refresh Icon\" image (default theme)"};
		{Text = "meafers",					Desc = "Suggested some stuff"};
		{Text = "Osyris",					Desc = "Wrote 't', an open-source typechecking library"};
		{Text = "buildthomas",				Desc = "Wrote 'MockDataStoreService', an open-source mock DataStoreService replacement library"};
		{Text = "Tiffany352",				Desc = "Wrote an improved base64 implementation"};
		{Text = "",							Desc = ""};
		{Text = "~ :) ~",					Desc = ""};
		{Text = "Donors",					Desc = "Donors keep the wheels turning ;)"};
		{Text = "The Users [You :)]",		Desc = "For using the script and keeping it alive :)"};
		{Text = "Special thanks", 			Desc = "Special thanks to everyone who helped along the way and suggested new ideas!"};
		{Text = "Not listed?",				Desc = "Message Davey_Bones and tell me what you need to be credited for and I'll add you in! (also sorry for missing you the first time)"};
	}
}
