return {
	Main = {
		{Text = "Sceleratis/Davey_Bones",	Desc = "Made Adonis & EISS"};
		{Text = "Kohltastrophe (Scripth)",	Desc = "For his help with various things and some code"};
		{Text = "einsteinK",			Desc = "Helped me with some scripting problems early in development and put together the LoadstringParser; Best programmer I know"};
		{Text = "Rerumu (Shining_Diamando)",	Desc = "Numerous contributions (Endless stairs, FiOne, Parser, Steampunk theme)"};
		{Text = "Cald_fan", 			Desc = "Community Maintainer & WebPanel Creator & Maintainer"};
		{Text = "joritochip",			Desc = "Community Maintainer & WebPanel Developer"};
		{Text = "Coasterteam",			Desc = "Community Maintainer & Development contributions (Kronos developer)"};
		{Text = "Expertcoderz",			Desc = "Community Maintainer & GitHub Contributor"};
	};
	GitHub = {
		{Text = "@GitHub MudockYatho", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub TheCakeChicken", 	Desc = "GitHub Contributor"};
		{Text = "@GitHub NNickey", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub ItsGJK", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub Kan18", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub Brandon-Beck", 	Desc = "GitHub Contributor"};
		{Text = "@GitHub GeneralScripter", 	Desc = "GitHub Contributor"};
		{Text = "@GitHub moo1210", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub kent911t", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub crywink", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub jaydensar", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub ccuser44",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Awesomewebm", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub TheLegendarySpark",	Desc = "GitHub Contributor"};
		{Text = "@GitHub DaEnder",		Desc = "GitHub Contributor"};
		{Text = "@GitHub pbstFusion",		Desc = "GitHub Contributor"};
		{Text = "@GitHub policetonyR",		Desc = "GitHub Contributor"};
		{Text = "@GitHub enescglyn",		Desc = "GitHub Contributor"};
		{Text = "@GitHub EpicFazbear",		Desc = "GitHub Contributor"};
		{Text = "@GitHub p3tray",		Desc = "GitHub Contributor"};
		{Text = "@GitHub okgabe",		Desc = "GitHub Contributor"};
		{Text = "@GitHub fxeP1",		Desc = "GitHub Contributor"};
		{Text = "@GitHub optimisticside",	Desc = "GitHub Contributor"};
		{Text = "@GitHub NeoInversion",		Desc = "GitHub Contributor"};
		{Text = "@GitHub imskyyc",		Desc = "GitHub Contributor"};
		{Text = "@GitHub LolloDev5123",		Desc = "GitHub Contributor"};
		{Text = "@GitHub happyman090",		Desc = "GitHub Contributor"};
		{Text = "@GitHub GalacticInspired",	Desc = "GitHub Contributor"};
		{Text = "@GitHub flgx16",		Desc = "GitHub Contributor"};
		{Text = "@GitHub DrewBokman",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Kw6m",			Desc = "GitHub Contributor"};
		{Text = "@GitHub chexburger",		Desc = "GitHub Contributor"};
		{Text = "@GitHub TjeerdoBoy112",	Desc = "GitHub Contributor"};
		{Text = "@GitHub Jack5079",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Bulldo344",		Desc = "GitHub Contributor"};
		{Text = "@GitHub evanultra01",		Desc = "GitHub Contributor"};
		{Text = "@GitHub SlipperySpelunky",	Desc = "GitHub Contributor"};
		{Text = "@GitHub c6lvnss",		Desc = "GitHub Contributor"};
		{Text = "@GitHub karl-police",		Desc = "GitHub Contributor"};
		{Text = "@GitHub CommodoreGamer118",	Desc = "GitHub Contributor"};
		{Text = "@GitHub spaggos",		Desc = "GitHub Contributor"};
		{Text = "@GitHub jun022222222",		Desc = "GitHub Contributor"};
		{Text = "@GitHub sea4h",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Tj33rd",		Desc = "GitHub Contributor"};
		{Text = "@GitHub L8X",			Desc = "GitHub Contributor"};
		{Text = "@GitHub Honzzzox",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Smaltin", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub NoUserSet", 		Desc = "GitHub Contributor"};
		{Text = "@GitHub xvarmkorv2",		Desc = "GitHub Contributor"};
		{Text = "@GitHub Quantify_RBLX",	Desc = "GitHub Contributor"};
	};
	Misc = {
		{Text = "Stravant/JustAPerson",				Desc = "Wrote LBI (no longer used)"};
		{Text = "darkelementallord",				Desc = "Updated some guis"};
		{Text = "TheFurryFish",					Desc = "Gave me some dank ideas like local particles and some loading related things; and helped debug"};
		{Text = "Moistality",					Desc = "Helped with finding and patching vulns"};
		{Text = "GigsD4X/F3X",					Desc = "F3X Building Tool"};
		{Text = "Drezmor",					Desc = "Resize was originally ripped from his ohgals and modified"};
		{Text = "KingKeith55",					Desc = "Provided the Stickify command"};
		{Text = "NickPatella",					Desc = "Made the piano used in the !piano command"};
		{Text = "Raspberry Pi/Raspy_Pi", 			Desc = "Made Dex explorer"};
		{Text = "j1my3p1x",					Desc = "His replication checking idea is what lead to the replication logs"};
		{Text = "Bubby4j",					Desc = "Used their \"Refresh Icon\" image (default theme)"};
		{Text = "meafers",					Desc = "Suggested some stuff"};
		{Text = "",						Desc = ""};
		{Text = "~ :) ~",					Desc = ""};
		{Text = "Donors",					Desc = "Donors keep the wheels turning ;)"};
		{Text = "The Users [You :)]",				Desc = "For using the script and keeping it alive :)"};
		{Text = "Special thanks", 				Desc = "Special thanks to everyone who helped along the way and suggested new ideas!"};
		{Text = "Not listed?",					Desc = "Message Davey_Bones and tell me what you need to be credited for and I'll add you in! (also sorry for missing you the first time)"};
	}
}
