--!strict
--[[
	Description: This file contains the keycode names for the QWERTY US keyboard.
	Author: github@ccuser44
	Date: 2022
	License: CC0
]]

return {
	[Enum.KeyCode.Space] = " ",
	[Enum.KeyCode.QuotedDouble] = "'",
	[Enum.KeyCode.Hash] = "3",
	[Enum.KeyCode.Dollar] = "4",
	[Enum.KeyCode.Percent] = "5",
	[Enum.KeyCode.Ampersand] = "7",
	[Enum.KeyCode.Quote] = "'",
	[Enum.KeyCode.LeftParenthesis] = "9",
	[Enum.KeyCode.RightParenthesis] = "0",
	[Enum.KeyCode.Asterisk] = "8",
	[Enum.KeyCode.Plus] = "=",
	[Enum.KeyCode.Comma] = ",",
	[Enum.KeyCode.Minus] = "-",
	[Enum.KeyCode.Period] = ".",
	[Enum.KeyCode.Slash] = "/",
	[Enum.KeyCode.Zero] = "0",
	[Enum.KeyCode.One] = "1",
	[Enum.KeyCode.Two] = "2",
	[Enum.KeyCode.Three] = "3",
	[Enum.KeyCode.Four] = "4",
	[Enum.KeyCode.Five] = "5",
	[Enum.KeyCode.Six] = "6",
	[Enum.KeyCode.Seven] = "7",
	[Enum.KeyCode.Eight] = "8",
	[Enum.KeyCode.Nine] = "9",
	[Enum.KeyCode.Colon] = ";",
	[Enum.KeyCode.Semicolon] = ";",
	[Enum.KeyCode.LessThan] = ",",
	[Enum.KeyCode.Equals] = "=",
	[Enum.KeyCode.GreaterThan] = ".",
	[Enum.KeyCode.Question] = "/",
	[Enum.KeyCode.At] = "2",
	[Enum.KeyCode.LeftBracket] = "[",
	[Enum.KeyCode.BackSlash] = "\\",
	[Enum.KeyCode.RightBracket] = "]",
	[Enum.KeyCode.Caret] = "6",
	[Enum.KeyCode.Underscore] = "-",
	[Enum.KeyCode.Backquote] = "`",
	[Enum.KeyCode.A] = "A",
	[Enum.KeyCode.B] = "B",
	[Enum.KeyCode.C] = "C",
	[Enum.KeyCode.D] = "D",
	[Enum.KeyCode.E] = "E",
	[Enum.KeyCode.F] = "F",
	[Enum.KeyCode.G] = "G",
	[Enum.KeyCode.H] = "H",
	[Enum.KeyCode.I] = "I",
	[Enum.KeyCode.J] = "J",
	[Enum.KeyCode.K] = "K",
	[Enum.KeyCode.L] = "L",
	[Enum.KeyCode.M] = "M",
	[Enum.KeyCode.N] = "N",
	[Enum.KeyCode.O] = "O",
	[Enum.KeyCode.P] = "P",
	[Enum.KeyCode.Q] = "Q",
	[Enum.KeyCode.R] = "R",
	[Enum.KeyCode.S] = "S",
	[Enum.KeyCode.T] = "T",
	[Enum.KeyCode.U] = "U",
	[Enum.KeyCode.V] = "V",
	[Enum.KeyCode.W] = "W",
	[Enum.KeyCode.X] = "X",
	[Enum.KeyCode.Y] = "Y",
	[Enum.KeyCode.Z] = "Z",
	[Enum.KeyCode.LeftCurly] = "[",
	[Enum.KeyCode.Pipe] = "\\",
	[Enum.KeyCode.RightCurly] = "]",
	[Enum.KeyCode.Tilde] = "`",
	[Enum.KeyCode.KeypadMinus] = "-",
	[Enum.KeyCode.KeypadPlus] = "+",
	[Enum.KeyCode.Print] = "*",
}
