# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: Sceleratis # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.roblox.com/game-pass/1348327/Adonis-Donor-Perks', 'https://www.roblox.com/catalog/6878510605/Adonis-Donor-Perks', 'https://www.roblox.com/game-pass/5212076/50-No-Perks', 'https://www.roblox.com/game-pass/5212077/100-No-Perks', 'https://www.roblox.com/game-pass/5212081/500-No-Perks'] # ['https://www.redbubble.com/people/Sceleratis/explore?asc=u&page=1&sortOrder=recent'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
