--[[
	If you want to learn how to modify Adonis, create plugins and/or themes;
	and add, remove and modify features and don't know where to start;
	or want to deepen your knowledge of the API, then the Adonis wiki is here to help.
	The wiki contains information about the Adonis API and how to use it;
	as well as information about settings and how to use Adonis.

	It can be viewed here: 
		https://github.com/Epix-Incorporated/Adonis/wiki
--]]
