blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Server
    url: https://discord.gg/H5RvTP3
    about: Please submit your questions here. Join our community for in-depth discussions and to easily contact Adonis maintainers.
    
