return {
    "";
    "ADONIS CRITICAL INCIDENT";
    "";
    "Adonis is currently running in restricted mode.";
    "Most features have been removed and Adonis can now only use core functions limited to basic user moderation functionality.";
    "A service failure event has occured, and Adonis has had to fall back to the backup. Error code: 1A.Rx503.";
    "Scroll down for a list of functionality losses.";
    "";
    "We are working hard to resolve the issue and normal operations will hopefully resume soon.";
    "See our offical group for more information.";
    "";
    "https://www.roblox.com/groups/886423/Epix-Incorporated";
    "";
    "Adonis functionality changes:";
    "";
    "Commands:";
    "";
    "Donors                 <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "Fun                    <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "Players                <font color = 'rgb(255, 162, 0)'>[Temporary loss of services. Essential commands remain.]</font>";
    "Moderators             <font color = 'rgb(255, 162, 0)'>[Temporary loss of services. Essential commands remain.]</font>";
    "Admins                 <font color = 'rgb(255, 162, 0)'>[Temporary loss of services. Essential commands remain.]</font>";
    "HeadAdmins             <font color = 'rgb(255, 162, 0)'>[Temporary loss of services. Essential commands remain.]</font>";
    "Creators               <font color = 'rgb(255, 162, 0)'>[Temporary loss of services. Essential commands remain.]</font>";
    "";
    "Settings:";
    "";
    "Theme                  <font color = 'rgb(255, 162, 0)'>[Has been forced to 'Default'.]</font>";
    "MobileTheme            <font color = 'rgb(255, 162, 0)'>[Has been forced to 'Default'.]</font>";
    "DefaultTheme           <font color = 'rgb(255, 162, 0)'>[Has been forced to 'Default'.]</font>";
    "SaveAdmins             <font color = 'rgb(255, 162, 0)'>[Has been forced to 'Default'.]</font>";
    "FunCommands            <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "PlayerCommands         <font color = 'rgb(0, 255, 0)'>[Has been forced enabled.]</font>";
    "CommandFeedback        <font color = 'rgb(0, 255, 0)'>[Has been forced enabled.]</font>";
    "CrossServerCommands    <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "ChatCommands           <font color = 'rgb(255, 162, 0)'>[Has been forced enabled.]</font>";
    "CodeExecution          <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "SilentCommandDenials   <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "Console                <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "Console_AdminsOnly     <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "HelpSystem             <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "HelpButton             <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "DonorCapes             <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "DonorCommands          <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "LocalCapes             <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "Detection              <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "CheckClients           <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "ExploitNotifications   <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "CharacterCheckLogs     <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiNoclip             <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiRootJointDeletion  <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiMultiTool          <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiGod                <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiSpeed              <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiBuildingTools      <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "AntiAntiIdle           <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "ExploitGuiDetection    <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "Notification           <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "G_API                  <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "G_Access               <font color = 'rgb(255, 162, 0)'>[Has been forced disabled.]</font>";
    "";
    "Core";
    "";
    "Server Plugins         <font color = 'rgb(0,255,0)'>[Services remain operational.]</font>";
    "Client Plugins         <font color = 'rgb(0,255,0)'>[Services remain operational.]</font>";
    "";
    "AntiExploit            <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "(SERVER)AntiCheat      <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "(CLIENT)AntiCheat      <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "HelpSystem             <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "WebPanel               <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "CrossServer Functions  <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "_G Services            <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
    "TrelloAPI              <font color = 'rgb(0,255,0)'>[Services remain operational.]</font>";
    "DataStore              <font color = 'rgb(0,255,0)'>[Services remain operational.]</font>";
    "";
    "Client:";
    "";
    "UI Themes              <font color = 'rgb(255,0,0)'>[Loss of services.]</font>";
}
