-- The order of each in-game settings editor setting is displayed.

-----------------------------------------
-- ORDER INGAMESETTINGSEDITOR SETTINGS --
-----------------------------------------

return {
	"HideScript";
	"DataStore";
	"DataStoreKey";
	"DataStoreEnabled";
	"LocalDatastore";
	" ";
	"Storage";
	"RecursiveTools";
	" ";
	"Theme";
	"MobileTheme";
	" ";
	"Ranks";
	" ";
	"Permissions";
	"Aliases";
	"Cameras";
	" ";
	"Commands";
	"Banned";
	"Muted";
	"Blacklist";
	"Whitelist";
	"MusicList";
	"CapeList";
	"InsertList";
	"Waypoints";
	"CustomRanks";
	" ";
	"OnStartup";
	"OnJoin";
	"OnSpawn";
	" ";
	"SaveAdmins";
	"WhitelistEnabled";
	" ";
	"Prefix";
	"PlayerPrefix";
	"SpecialPrefix";
	"SplitKey";
	"BatchKey";
	"ConsoleKeyCode";
	" ";
	"HttpWait";
	"Trello_Enabled";
	"Trello_Primary";
	"Trello_Secondary";
	"Trello_AppKey";
	"Trello_Token";
	"Trello_HideRanks";
	" ";
	"G_API";
	"G_Access";
	"G_Access_Key";
	"G_Access_Perms";
	"Allowed_API_Calls";
	" ";
	"FunCommands";
	"PlayerCommands";
	"AgeRestrictedCommands";
	"WarnDangerousCommand";
	"CommandFeedback";
	"CrossServerCommands";
	"ChatCommands";
	"";
	"SilentCommandDenials";
	"OverrideChatCallbacks";
	" ";
	"BanMessage";
	"LockMessage";
	"SystemTitle";
	" ";
	"MaxLogs";
	"SaveCommandLogs";
	"Notification";
	"SongHint";
	"TopBarShift";
	"DefaultTheme";
	"ReJail";
	"";
	"AutoClean";
	"AutoCleanDelay";
	"AutoBackup";
	" ";
	"PlayerList";
	"Console";
	"Console_AdminsOnly";
	" ";
	"HelpSystem";
	"HelpButton";
	"HelpButtonImage";
	" ";
	"DonorCommands";
	"DonorCapes";
	"LocalCapes";
	" ";
	"AllowClientAntiExploit";
	"Detection";
	"CheckClients";
	" ";
	"ExploitNotifications";
	"CharacterCheckLogs";
	"AntiNoclip";
	"AntiRootJointDeletion";
	"AntiMultiTool";
	"AntiGod";
	" ";
	"AntiSpeed";
	"AntiBuildingTools";
	"AntiAntiIdle";
};