return {
	{Text = "Sceleratis/Davey_Bones",	Desc = "Made Adonis & EISS"};
	{Text = "Kohltastrophe (Scripth)",	Desc = "For his help with various things and some code"};
	{Text = "einsteinK",				Desc = "Helped me with some scripting problems early in development and put together the LoadstringParser; Best scripter I know"};
	{Text = "Rerumu (Shining_Diamando)",Desc = "Made the endless stairs place\nRerubi (Bytecode Interpreter)\nParser\nSteampunk theme"};
	{Text = "@GitHub MudockYatho", 		Desc = "GitHub Contributor"};	
	{Text = "@GitHub TheCakeChicken", 	Desc = "GitHub Contributor"};
	{Text = "@GitHub NNickey", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub ItsGJK", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub Kan18", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub Brandon-Beck", 	Desc = "GitHub Contributor"};
	{Text = "@GitHub GeneralScripter", 	Desc = "GitHub Contributor"};
	{Text = "@GitHub moo1210", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub kent911t", 		Desc = "GitHub Contributor"};
	{Text = "@GitHub Kan18", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub crywink", 			Desc = "GitHub Contributor"};
	{Text = "@GitHub jaydensar", 		Desc = "GitHub Contributor"};
	{Text = "@GitHub Awesomewebm", 		Desc = "GitHub Contributor"};
	{Text = "@GitHub TheLegendarySpark",Desc = "GitHub Contributor"};
	{Text = "Stravant/JustAPerson/Jason Priest (?)", Desc = "Wrote LBI (No longer used)"};	
	{Text = "darkelementallord",		Desc = "Updated some guis"};
	{Text = "TheFurryFish",				Desc = "Gave me some dank ideas like local particles and some loading related things; and helped debug"};
	{Text = "Moistality",				Desc = "Helped with finding and patching vulns"};
	{Text = "GigsD4X/F3X",				Desc = "F3X Building Tool"};
	{Text = "Drezmor",					Desc = "Resize was originally ripped from his ohgals and modified"};
	{Text = "KingKeith55",				Desc = "Provided the Stickify command"};
	{Text = "NickPatella",				Desc = "Made the piano used in the !piano command"};
	{Text = "Raspberry Pi/Raspy_Pi", 	Desc = "Made Dex"};
	{Text = "j1my3p1x",					Desc = "His replication checking idea is what lead to the replication logs"};
	{Text = "Bubby4j",					Desc = "Used their \"Refresh Icon\" image"};
	{Text = "meafers",					Desc = "Suggested some stuff"};
	{Text = "Donors",					Desc = "Donors keep the wheels turning ;)"};
	{Text = "The Users [You :)]",		Desc = "For using the script and keeping it alive :)"};
	{Text = "Special thanks", 			Desc = "Special thanks to everyone who helped along the way and suggested new ideas!"};
	{Text = "Not listed?",				Desc = "Message me and tell me what you need to be credited for and I'll add you in!"};
}
