name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: rojo upload --cookie "${{ secrets.ROBLOSECURITY }}" --asset_id 7510592873 .github/deploy.project.json
